# Generated by Django 2.2 on 2019-04-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='fname', max_length=100)),
                ('last_name', models.CharField(db_column='lname', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_type', models.CharField(choices=[('staff', 'Staff'), ('professor', 'Professor'), ('student', 'Student'), ('driver', 'Driver')], db_column='subtype', max_length=20)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
