# Generated by Django 2.2 on 2019-04-11 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfCartRideAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', unique=True)),
                ('position', models.CharField(blank=True, max_length=55, null=True)),
                ('is_admin', models.BooleanField(db_column='isAdmin', default=False)),
                ('department', models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfCartRideAPI.Department')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
