# Generated by Django 2.2 on 2019-04-11 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfCartRideAPI', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', unique=True)),
                ('date_hired', models.DateField(db_column='dateHired', default=None)),
                ('license_number', models.CharField(db_column='licenseNum', max_length=100)),
            ],
            options={
                'db_table': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='GolfCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('num_seats', models.IntegerField(db_column='numSeats')),
            ],
            options={
                'db_table': 'GolfCart',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.CharField(default=None, max_length=100)),
                ('latitude', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_column='startTime')),
                ('end_time', models.DateTimeField(db_column='endTime')),
                ('is_completed', models.BooleanField(db_column='isCompleted', default=False)),
                ('driver', models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.DO_NOTHING, to='golfCartRideAPI.Driver')),
                ('end_location', models.ForeignKey(db_column='end_location_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='end_location_set', to='golfCartRideAPI.Location')),
                ('golf_cart', models.ForeignKey(db_column='golfcart_id', on_delete=django.db.models.deletion.DO_NOTHING, to='golfCartRideAPI.GolfCart')),
                ('rider', models.ForeignKey(db_column='rider_id', on_delete=django.db.models.deletion.DO_NOTHING, to='golfCartRideAPI.Person')),
                ('start_location', models.ForeignKey(db_column='start_location_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='start_location_set', to='golfCartRideAPI.Location')),
            ],
            options={
                'db_table': 'Ride',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', unique=True)),
                ('birth_date', models.DateField(db_column='birthdate', default=None)),
                ('grad_year', models.CharField(db_column='gradYear', max_length=20)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, to='golfCartRideAPI.Department')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='golfCartRideAPI.Student')),
            ],
            options={
                'db_table': 'StudentDepartment',
            },
        ),
        migrations.CreateModel(
            name='RideRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_date', models.DateField(db_column='completeDate')),
                ('rating', models.IntegerField()),
                ('ride', models.ForeignKey(db_column='ride_id', on_delete=django.db.models.deletion.DO_NOTHING, to='golfCartRideAPI.Ride')),
            ],
            options={
                'db_table': 'RideRating',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', unique=True)),
                ('title', models.CharField(default=None, max_length=55)),
                ('is_full_time', models.BooleanField(db_column='isFullTime', default=False)),
                ('department', models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfCartRideAPI.Department')),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='golf_cart',
            field=models.ForeignKey(db_column='golfcart_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='golfCartRideAPI.GolfCart'),
        ),
    ]
