# Generated by Django 2.2 on 2019-04-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golfCartRideAPI', '0004_auto_20190411_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='golfCartRideAPI.Person', verbose_name='Person'),
        ),
    ]
