# Generated by Django 2.2 on 2019-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfCartRideAPI', '0005_auto_20190411_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='golfcart',
            old_name='model',
            new_name='cart_model',
        ),
        migrations.AlterField(
            model_name='golfcart',
            name='cart_model',
            field=models.CharField(db_column='model', max_length=100),
        ),
    ]
