# Generated by Django 2.2 on 2019-04-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfCartRideAPI', '0006_auto_20190412_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(db_column='status', default='pending', max_length=100),
        ),
    ]
